# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-09 20:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainmap', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='source',
            field=models.CharField(choices=[('\u0410\u0440\u0445\u0438\u0432', '\u0410\u0440\u0445\u0438\u0432'), ('\u041b\u0438\u0447\u043d\u044b\u0439 \u0430\u0440\u0445\u0438\u0432', '\u041b\u0438\u0447\u043d\u044b\u0439 \u0430\u0440\u0445\u0438\u0432'), ('\u0418\u043d\u0442\u0435\u0440\u043d\u0435\u0442 \u0438\u0441\u0442\u043e\u0447\u043d\u0438\u043a', '\u0418\u043d\u0442\u0435\u0440\u043d\u0435\u0442 \u0438\u0441\u0442\u043e\u0447\u043d\u0438\u043a'), ('\u041d\u0435\u0438\u0437\u0432\u0435\u0441\u0442\u043d\u043e', '\u041d\u0435\u0438\u0437\u0432\u0435\u0441\u0442\u043d\u043e')], default='\u041d\u0435\u0438\u0437\u0432\u0435\u0441\u0442\u043d\u043e', max_length=32),
        ),
        migrations.AlterField(
            model_name='photo',
            name='image',
            field=models.ImageField(upload_to='photos'),
        ),
    ]
